import { PageHero } from "../components/page-hero";
import { RouteShell } from "../components/route-shell";

const mapUrl = "https://maps.app.goo.gl/nEpBEN1w4nR1vwmm7";
const businessAddress = "Charsadda Road, Toady Stop, Peshawar, Charsadda Road, Sha Alum Pull, near Sha Alum Pull, Peshawar, 25000, Pakistan";
const mapEmbedUrl = `https://www.google.com/maps?q=${encodeURIComponent(businessAddress)}&output=embed`;
const facebookUrl = "https://www.facebook.com/profile.php?id=61594251901318&sk=followers";

const team = [
  { name: "Muntazir Khan", role: "Owner", mobile: "03239693972", whatsapp: "923239693972", initials: "MK" },
  { name: "Azaz Ali", role: "Partner", mobile: "03009700227", whatsapp: "923009700227", initials: "AA" },
  { name: "Abd Ullah", role: "Team Member", mobile: "03251851838", whatsapp: "923251851838", initials: "AU" },
];

export default function AboutPage() {
  return <RouteShell><main className="about-page"><PageHero eyebrow="ABOUT MUNTAZIR & SONS" title={<>Furniture that <i>stays with you.</i></>} copy="Muntazir & Sons Furniture is a family furniture house from Peshawar, making rooms feel more like home for nearly four decades." image="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=85" /><section className="about-intro"><div><p className="eyebrow">OUR STORY</p><h2>A furniture house built around people and place.</h2></div><p>We bring together honest materials, modern silhouettes, and the warmth of local craft. Every piece is chosen for its character, comfort, and staying power.</p></section><section className="about-location"><div className="about-location-copy"><p className="eyebrow">FIND US IN PESHAWAR</p><h2>Come see what feels right.</h2><div className="about-detail"><i className="icon fa-solid fa-building" /><div><strong>Business</strong><span>Muntazir & Sons Furniture</span></div></div><div className="about-detail"><i className="icon fa-solid fa-location-dot" /><div><strong>Address</strong><span>{businessAddress}</span></div></div><a className="button button-primary about-map-button" href={mapUrl} target="_blank" rel="noreferrer">Open in Google Maps <i className="icon fa-solid fa-arrow-up-right-from-square" /></a></div><div className="about-map"><iframe src={mapEmbedUrl} title="Muntazir & Sons Furniture on Google Maps" loading="lazy" allowFullScreen /></div></section><section className="about-team"><div className="about-section-heading"><div><p className="eyebrow">THE PEOPLE BEHIND THE PIECES</p><h2>Meet the team.</h2></div><a className="about-social" href={facebookUrl} target="_blank" rel="noreferrer"><i className="icon fa-brands fa-facebook-f" /> Follow us on Facebook</a></div><div className="about-team-grid">{team.map((member) => <article className="about-team-card" key={member.name}><div className="about-profile-placeholder" role="img" aria-label={`${member.name} profile placeholder`}><span>{member.initials}</span><i className="icon fa-solid fa-user" /></div><div className="about-team-info"><p className="eyebrow">{member.role}</p><h3>{member.name}</h3><div className="about-contact-actions"><a className="about-phone" href={`tel:${member.mobile}`}><i className="icon fa-solid fa-phone" /> {member.mobile}</a><a className="about-whatsapp" href={`https://wa.me/${member.whatsapp}`} target="_blank" rel="noreferrer" aria-label={`Message ${member.name} on WhatsApp`}><i className="icon fa-brands fa-whatsapp" /> WhatsApp</a></div></div></article>)}</div></section></main></RouteShell>;
}
